import 'package:hach4happ/Workout/work.dart';

List<Work> breathing = [
  Work(
      name: "Abdominal breathing technique",
      image: 'assets/images/breathing_2.png',
      disc:
      "The abdominal breathing technique can be really helpful before experiencing a particularly stressful event like taking an exam or giving a big presentation. Oy, our hearts are pounding just thinking about it. Put one hand on your belly just below your ribs and the other hand on your chest. Take a deep breath in through your nose, and let your belly push your hand out. Your chest should not move. Breathe out through pursed lips as if you were whistling."),
  Work(
      name: "Progressive muscle relaxation",
      image: 'assets/images/breathing_4.png',
      disc:
      "How to do it: Close your eyes and focus on tensing and relaxing each muscle group for 2 to 3 seconds. Start with your feet and toes, and then move up to your knees, thighs, glutes, chest, arms, hands, neck, jaw, and eyes. Maintain deep, slow breaths the entire time. In progressive muscle relaxation, you tense a group of muscles as you breathe in, and you relax them as you breathe out. You work on your muscle groups in a certain order."),
  Work(
      name: "Alternate nostril breathing",
      image: 'assets/images/breathing_5.jpeg',
      disc:
      "How to do it: Start by sitting in a comfortable meditative pose. Hold out your dominant hand and press the tips of your pointer and middle fingers into your palm, leaving your ring finger, pinky finger, and thumb extended. You can use this breathing technique to help manage stresses in your daily life. You may also find that practicing alternate nostril breathing helps you to be more mindful of the present moment."),
  Work(
      name: "Skull-Shining Breath",
      image: 'assets/images/breathing_6.jpeg',
      disc:
      "How to do it: Begin sitting in an upright position with good posture and your hands on your knees. Take a long, slow inhale through your nose. Then exhale powerfully (also through your nose) by contracting your lower belly. Kapalabhati consists of alternating short, explosive exhales and slightly longer, passive inhales. Exhales are generated by powerful contractions of the lower belly (between the pubis and navel), which push air out of the lungs.")
];

List<Work> stretch = [
  Work(
      name: "Knee to Chest Stretch",
      image: 'assets/images/stretching_1.jpeg',
      disc:
      "Lie on your back with both legs extended.Pull your right knee into your chest, while keeping the left leg straight and your lower back pressed into the floor.Hold for 30 seconds to 2 minutes.Repeat on the other leg"),
  Work(
      name: "Lunging Hip Flexor Stretch",
      image: 'assets/images/stretching_2.jpeg',
      disc:
      "Kneel on your left knee. Place your right foot flat on the floor in front of you, knee bent. One of the hip flexors is the psoas muscle. You have one on each side of your body, each working to lift your thigh to your torso."),
  Work(
      name: "Seated Shoulder Squeeze",
      image: 'assets/images/stretching_3.png',
      disc:
      "Sit on the floor, chair or stability ball with knees bent, and feet flat. Clasp hands together behind the lower back. Straighten arms, while squeezing shoulders blades together. Hold a few seconds then release, and keep repeating."),
  Work(
      name: "Lying Quad Stretch",
      image: 'assets/images/stretching_5.jpeg',
      disc: "Lie in a face-down position, propping your head on your left hand. Alternatively, you can lie on your side to perform this stretch. After a couple of seconds, pull your right foot toward your butt and bend your left knee to stabilize yourself."),
];
List<Work> yoga = [
  Work(
      name: "Vrikshasana",
      image: 'assets/images/yoga_1.jpeg',
      disc:
      "This pose gives you a sense of grounding. It improves your balance and strengthens your legs and back. In the beginning, you might find it difficult to bring the left foot above the right knee. In such cases, you can place your foot below the knee. But, as mentioned earlier, never place the foot on your knee."),
  Work(
      name: "Kursiasana",
      image: 'assets/images/yoga_2.jpeg',
      disc:
      "An intensely powerful pose, this one strengthens the muscles of the legs and arms. Utkatasana, also called Kursiasana or Chair pose is a standing yoga posture that strengthens the core and lower body. In this pose, hands are kept straight and palms faces downward, while the knees bend as if sitting on an imaginary chair."),
  Work(
      name: "Naukasana",
      image: 'assets/images/yoga_3.png',
      disc:
      "It tightens the abdominal muscles and strengthens shoulders and upper back. Naukasana comes from the two Sanskrit words 'nauka' which means 'boat' and 'asana' meaning 'posture' or 'seat'. It is a posture in which our body takes the shape of a boat."),
  Work(
      name: "Child's Pose",
      image: 'assets/images/yoga_4.jpeg',
      disc:
      "This restful posture helps let go and surrender. It restores vitality physically, mentally and emotionally. Bālāsana, Child's Pose, or Child's Resting Pose is a kneeling asana in modern yoga as exercise. Balasana is a counter asana for various asanas and is usually practiced before and after Sirsasana.")
];

List<Work> food = [
  Work(
      name: "Protein Diet",
      image: 'assets/images/food_1.jpeg',
      disc:
      "Proteins are made up of smaller building blocks called amino acids. There are 23 different amino acids, some of which your body can synthesize and others that you must get from food.One amino acid called tyrosine plays a critical role in the production of dopamine."),
  Work(
      name: "Less Saturated Fat",
      image: 'assets/images/food_2.jpeg',
      disc:
      "Some animal research has found that saturated fats, such as those found in animal fat, butter, full-fat dairy, palm oil and coconut oil, may disrupt dopamine signaling in the brain when consumed in very large quantities."),
  Work(
      name: "Velvet Beans",
      image: 'assets/images/food_3.jpeg',
      disc:
      "Velvet beans, also known as Mucuna pruriens, naturally contain high levels of L-dopa, the precursor molecule to dopamine Studies show that eating these beans may help raise dopamine levels naturally, especially in people with Parkinson’s disease, a movement disorder caused by low dopamine levels."),
  Work(
      name: "Probiotics",
      image: 'assets/images/food_4.png',
      disc:
      "Probiotics are live bacteria and yeasts that are good for you, especially your digestive system. We usually think of these as germs that cause diseases. But your body is full of bacteria, both good and bad. Probiotics are often called good or helpful bacteria because they help keep your gut healthy.")
];